refact: support combined short flags

diff --git a/bin/refact b/bin/refact
--- a/bin/refact
+++ b/bin/refact
@@ -3,7 +3,7 @@
 function mshex.yn {
   local prompt_yn='yes/no'
   local ret_default=
-  case "$1" in
+  case $1 in
   -y)
     ret_default=0
     prompt_yn='Yes/no'
@@ -76,73 +76,115 @@ OPTIONS
 EOF
 }
 
-opt_options_end=
+## @var flags
+##   E ... argument parse error
+##   H ... show help
+##   S ... literal option "--"
+##   b ... matches the word boundaries
+##   c ... check collisions
+flags=
 
-grc_options=(-U)
+before=
+after=
 inputfiles=()
 
+grc_options=(-U)
 regex_type=E
 
-fB=
-fSkipColl=
+function refact/read-arguments/error {
+  echo "refact: $1" >&2
+  flags=E$flags
+}
 
-flagHelp=
-flagError=
-before= flagBeforeSpecified=
-after=  flagAfterSpecified=
-while (($#)); do
-  declare arg="$1"; shift
-  if [[ ! $opt_options_end && $arg == -* ]]; then
-    case "$arg" in
-    (-b|--word-boundary)    fB=1 ;;
-    (-B|--no-word-boundary) fB= ;;
-    (--skip-collisions)     fSkipColl=1 ;;
-    (-F|--fixed-strings) regex_type=F ;;
-    (-Wg,?*)
-      IFS=, builtin eval 'grc_options+=(${arg:4})' ;;
-    (--help)
-      flagHelp=1 ;;
-    (--) opt_options_end=1 ;;
-    (-*)
-      echo "refact: unknown option ($arg)." >&2
-      flagError=1 ;;
-    esac
-  else
-    if [[ ! $flagBeforeSpecified ]]; then
-      before=$arg
-      flagBeforeSpecified=1
-    elif [[ ! $flagAfterSpecified ]]; then
-      after=$arg
-      flagAfterSpecified=1
-    else
-      if [[ ! -f $arg ]]; then
-        if [[ -e $arg ]]; then
-          echo "refact: the specified path \`$arg' is not a regular file." >&2
-        else
-          echo "refact: the specified file \`$arg' does not exist." >&2
-        fi
-        flagError=1
+function refact/read-arguments/option:W {
+  case $1 in
+  (g,?*)
+    IFS=, builtin eval 'grc_options+=(${arg:4})' ;;
+  (*)
+    refact/read-arguments/error "unrecognized option '-W$1'" ;;
+  esac
+}
+
+function refact/read-arguments {
+  flags=c
+
+  local -a words=()
+  local iword=0
+  while (($#)); do
+    local arg=$1; shift
+    if [[ $flags != *S* && $arg == -?* ]]; then
+      if [[ $arg == --* ]]; then
+        case $arg in
+        (--word-boundary)    arg=-b ;;
+        (--no-word-boundary) arg=-B ;;
+        (--fixed-strings)    arg=-F ;;
+        (--help)             flags=H$flags; continue ;;
+        (--skip-collisions)  flags=${flags//c}; continue ;;
+        (--) flags=S$flags; continue ;;
+        (*)
+          refact/read-arguments/error "unrecognized long option '$arg'."
+          continue ;;
+        esac
       fi
-      inputfiles[${#inputfiles[@]}]=$arg
+
+      arg=${arg:1}
+      while [[ $arg ]]; do
+        local c=${arg::1} arg=${arg:1}
+        case $c in
+        (b) flags=b$flags ;;
+        (B) flags=${flags//b} ;;
+        (F) regex_type=F ;;
+        (W)
+          if [[ ! $arg ]]; then
+            if (($#==0)); then
+              refact/read-arguments/error "missing option argument for '-$c'"
+              break
+            fi
+            arg=$1; shift
+          fi
+          refact/read-arguments/process:"$c" "$arg"
+          break ;;
+        (*)
+          refact/read-arguments/error "unrecognized option '-$c'." ;;
+        esac
+      done
+    else
+      words[iword++]=$arg
     fi
+  done
+
+  ((iword>=1)) || refact/read-arguments/error 'pattern is not specified.'
+  ((iword>=2)) || refact/read-arguments/error 'refact: pattern is not specified.'
+  before=${words[0]}
+  after=${words[1]}
+
+  local file
+  for file in "${words[@]:2}"; do
+    if [[ ! -f $file ]]; then
+      if [[ -e $file ]]; then
+        refact/read-arguments/error "the specified path \`$file' is not a regular file."
+      else
+        refact/read-arguments/error "the specified file \`$file' does not exist."
+      fi
+    fi
+    inputfiles[${#inputfiles[@]}]=$file
+  done
+
+  if [[ $flags == *E* ]]; then
+    usage_exit
+    return 2
   fi
-done
+}
 
-if [[ $flagHelp ]]; then
+refact/read-arguments "$@" || exit 2
+
+if [[ $flags == *H* ]]; then
   print_help
-  [[ ! $flagError ]]
-  exit
+  exit 0
 fi
 
-[[ $flagBeforeSpecified && $flagAfterSpecified ]] || flagError=1
-
-if [[ $flagError ]]; then
-  usage_exit
-  exit "$flagError"
-fi
-
-# for debug
-# fB=
+# For debug
+# flags=b
 # before=Check
 # after=_check
 
@@ -216,7 +258,7 @@ if [[ $regex_type == F ]]; then
   bpat=$ret
 fi
 
-if [[ $fB ]]; then
+if [[ $flags == *b* ]]; then
   [[ $bpat =~ ^[_[:alnum:]] ]] && bpat='\b'"$bpat"
   [[ $bpat =~ [_[:alnum:]]$ ]] && bpat="$bpat"'\b'
 
@@ -327,9 +369,9 @@ enumerate_matches.i2
 if ((${#target_files[@]} <= 0)); then
   echo '---------------------------'
   echo "refact: pattern ($bpat) not found!" >&2
-  exit 2
+  exit 1
 fi
-if [[ $apat && ! $fSkipColl ]]; then
+if [[ $apat && $flags == *c* ]]; then
   echo '------- collision? --------'
   grc --color=auto "${grc_options[@]}" "$apat" "${inputfiles[@]}"
 fi
