ren: clean up

diff --git a/bin/ren b/bin/ren
--- a/bin/ren
+++ b/bin/ren
@@ -102,14 +102,17 @@ function mshex.yn {
   local prompt_yn='yes/no'
   local ret_default=
   case "$1" in
-  -y)
+  (-y)
     ret_default=0
     prompt_yn='Yes/no'
     shift ;;
-  -n)
+  (-n)
     ret_default=1
     prompt_yn='yes/No'
     shift ;;
+  (*)
+    echo 'msehx.yn: invalid usage!' >&2
+    exit 1 ;;
   esac
 
   while read -ep "$* ($prompt_yn): " line; do
@@ -129,19 +132,17 @@ function mshex.yn {
       fi ;;
     esac
   done
+
+  return 1
 }
 
-mv_option=-n
-
-srclist=()
-dstlist=()
 
 ## 関数 check_overwrite
-## @var[in] src
-## @var[in] dst
-## @var[in] dstlist
-## @var[in] fBackupSuffix
-## @var[in] qsrc,qdst,q,Q
+## @var[in]     src,dst
+## @var[in]     fBackupSuffix
+## @var[in,out] srclist,dstlist
+## @var[out]    mv_option
+## @var[in]     qsrc,qdst,q,Q
 function check_overwrite {
   # check collision
   local other_dst flag_collision=0
@@ -183,93 +184,101 @@ function check_overwrite {
   return 0
 }
 
-function register_mvlist {
-  local q=\' Q=\'\\\'\'
+exec 3<&0
 
-  while read -r src && read -r dst; do
-    [[ -e "$src" ]] || continue
-
-    [[ $fEval ]] && IFS= GLOBIGNORE=\* eval "dst=($dst)"
-
-    local qsrc=${src//$q/$Q}
-    local qdst=${dst//$q/$Q}
-
-    check_overwrite || continue
-
-    srclist+=("$src")
-    dstlist+=("$dst")
-    printf "mv '%s' '%s'\n" "$qsrc" "$qdst"
-  done
-}
-
-register_mvlist < <(
+## 関数 _ren
+## @var[in] files[@]
+function _ren {
   # ※ファイル名に改行が含まれていると駄目
   printf '%s\n' "${files[@]}" | awk '
     #-------------------------------------------------------------------------------
     # replace
-    function replace(text,before,after, _is_tmpl,_is_head,_captures,_rep,_ltext,_rtext){
-      _is_tmpl=(match(after,/\$[0-9]+/)>0);
-      _is_head=(substr(before,1,1)=="^");
-
-      _ret="";
-      while(match(text,before,_captures)>0){
-        _ltext=substr(text,1,RSTART-1);
-        _rtext=substr(text,RSTART+RLENGTH);
+    function replace(text, before, after,  _is_tmpl, _is_head, _captures, _rep, _ltext, _rtext) {
+      _is_tmpl = (match(after, /\$[0-9]+/) > 0);
+      _is_head = (substr(before, 1, 1) == "^");
+  
+      _ret = "";
+      while (match(text, before, _captures) > 0) {
+        _ltext = substr(text, 1, RSTART - 1);
+        _rtext = substr(text, RSTART + RLENGTH);
     
-        _rep=_is_tmpl?rep_instantiate_tmpl(after,_captures):after;
+        _rep = _is_tmpl? rep_instantiate_tmpl(after, _captures): after;
     
-        _ret=_ret _ltext _rep;
-        text=_rtext;
-
-        if(_is_head)break;
-        if(RLENGTH==0){
-          _ret=_ret substr(text,1,1);
-          text=substr(text,2);
-          if(length(text)==0)break;
+        _ret = _ret _ltext _rep;
+        text = _rtext;
+  
+        if (_is_head) break;
+        if (RLENGTH == 0) {
+          _ret = _ret substr(text, 1, 1);
+          text = substr(text, 2);
+          if (length(text) == 0) break;
         }
       }
       return _ret text;
     }
-    function rep_instantiate_tmpl(text,captures,  _ret,_num){
-      _ret="";
-      while(match(text,/\$([0-9]+)/,_num)){
+    function rep_instantiate_tmpl(text, captures,  _ret, _num) {
+      _ret = "";
+      while (match(text, /\$([0-9]+)/, _num)) {
         #print "dbg: $ captured: RSTART=" RSTART "; num=" _num[1] "; captures[num]=" captures[_num[1]] > "/dev/stderr"
-        _ret=_ret substr(text,1,RSTART-1) captures[_num[1]];
-        text=substr(text,RSTART+RLENGTH);
+        _ret = _ret substr(text, 1, RSTART - 1) captures[_num[1]];
+        text = substr(text, RSTART + RLENGTH);
       }
       return _ret text;
     }
-
-    BEGIN{
-      g_before=ENVIRON["ren_before"];
-      g_after =ENVIRON["ren_after"];
+  
+    BEGIN {
+      g_before = ENVIRON["ren_before"];
+      g_after  = ENVIRON["ren_after"];
     }
     {
-      q=0x27;
-      src=$0;
-      dst=replace($0,g_before,g_after);
-
-      if(src!=dst){
-        # printf("mv -n %c%s%c %c%s%c\n",q,src,q,q,dst,q);
-
-        # gsub("[\"\\\\$]","\\\\&",src);
-        # gsub("[\"\\\\$]","\\\\&",dst);
-        # printf("mv -n \"%s\" \"%s\"\n",src,dst);
-
+      q = 0x27;
+      src = $0;
+      dst = replace($0, g_before, g_after);
+  
+      if (src!=dst) {
+        # printf("mv -n %c%s%c %c%s%c\n", q, src, q, q, dst, q);
+  
+        # gsub("[\"\\\\$]", "\\\\&", src);
+        # gsub("[\"\\\\$]", "\\\\&", dst);
+        # printf("mv -n \"%s\" \"%s\"\n", src, dst);
+  
         print src;
         print dst;
       }
     }
-  '
-)
+  ' | {
+    mv_option=-n
+    srclist=()
+    dstlist=()
 
-if ((${#srclist[@]}==0)); then
-  echo "ren: files to change do not exist."
-  exit
-fi
+    local q=\' Q=\'\\\'\'
+  
+    while read -r src && read -r dst; do
+      [[ -e "$src" ]] || continue
+  
+      [[ $fEval ]] && IFS= GLOBIGNORE=\* eval "dst=($dst)"
+  
+      local qsrc=${src//$q/$Q}
+      local qdst=${dst//$q/$Q}
+  
+      check_overwrite || continue
+  
+      srclist+=("$src")
+      dstlist+=("$dst")
+      printf "mv '%s' '%s'\n" "$qsrc" "$qdst"
+    done
+  
+    if ((${#srclist[@]}==0)); then
+      echo "ren: files to change do not exist."
+      exit
+    fi
+  
+    mshex.yn -n "execute rename? " 0<&3 || exit 0
+  
+    for ((i=0,iN=${#srclist[@]};i<iN;i++)); do
+      mv $mv_option -v "${srclist[i]}" "${dstlist[i]}"
+    done
+  }
+}
 
-mshex.yn -n "execute rename? " || exit 0
-
-for ((i=0,iN=${#srclist[@]};i<iN;i++)); do
-  mv $mv_option -v "${srclist[i]}" "${dstlist[i]}"
-done
+_ren
